name: Around 3D
favicon: null
layout_spectrum: 0.73149
typography_spectrum: 0.17089
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00ffda'
    - '#000000'
    - '#008080'
    - '#005555'
    - '#00aaaa'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
