name: Around 3D
favicon: null
layout_spectrum: 0.01565
typography_spectrum: 0.17691
title: Around Media 3D
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00ffda'
    - '#000000'
    - '#008080'
    - '#005555'
    - '#00aaaa'
  brandStrength: 0
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
