name: Around 3D
favicon: null
layout_spectrum: 1
typography_spectrum: 0.17089
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4e4e4e'
    - '#00ffda'
    - '#000000'
    - '#2b2b2b'
    - '#00ff00'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
