name: Around 3D
favicon: null
layout_spectrum: 0.026231518713757396
typography_spectrum: 0.47310991445556283
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 1
  lightness: 0.41065455158241093
  saturation: 0.9698567984160036
  rhythmicContrast: 0.15856930147856474
purpose: []
